version: '3'
services:
 
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3308:3306"
  server:
    image: capstone-server:latest
    container_name: server
    restart: always
    ports:
      - "7000:7000"

