version: '3'
services:
 
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    networks:
      - capstone
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3308:3306"
       
networks:
  capstone:
    name: capstone

